nodeLinker: node-modules

# Security settings
enableStrictSsl: true
enableScripts: true

# Developer experience
preferInteractive: false
enableProgressBars: true

enableImmutableInstalls: ${CI:-false}

# Privacy
enableTelemetry: false

httpTimeout: 60000
